api:
  enabled: true
  address: '127.0.0.1' # ip address to bind (default: any)
  port: 9013
  mode: 'release'

log:
  format: "string" # string or json
  access_log: "stdout" # stdout: output to console, or define log path like "log/access_log"
  access_level: "info"
  error_log: "stderr" # stderr: output to console, or define log path like "log/error_log"
  error_level: "error"
  agent:
    enabled: false
    dsn: 'udp://logstash.example.com:8911'
    app_id: dandelion-seed
    #host: '' # log host, defaults to os.Getenv("HOST") or os.Hostname()
    #instance_id: '' # log instance_id, defaults to os.Getenv("INSTANCE_ID") or os.Hostname()

dandelion:
  url: 'http://127.0.0.1:9012'

kafka:
  enabled: false # default: false
  topic: test
  #group_id: test1 # defaults to os.Getenv("INSTANCE_ID") or os.Hostname()
  servers:
    - 127.0.0.1:9092

# multiple configs for different apps
configs:
  - app_id: test
    path: /tmp/test
    #chown: 'www' # does not work for windows
    #chmod: '664' # does not work for windows
    meta_files:
      - "package.json"
    exec_reload: 'echo 1'
